### PR TITLE
Update link to latest testing version 10.0.3beta

### PR DESCRIPTION
**Pull request by PVince81**

### CODE REVIEW

**Comment by PVince81** [comment]
@crrodriguez deploy ?

**Comment by lefherz** [comment]
did you test on staging? with the RC1 of the latest client the link didn't work at first.

**Comment by PVince81** [comment]
good point... and now I see that I put in the wrong link

**Comment by jnweiger** [comment]
sidenote: we had a broken download.org mirror until this morning. (there was a 1 out of 4 chance to fail)

**Pull request merged**
