### PR TITLE
Fixing stuff in the new history timeline

### PR DESCRIPTION
**Pull request by jospoortvliet**
- [x] fix ( and )'s

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Continuing work on #687

**Comment by jospoortvliet** [comment]
Amazingly, I fixed the problem with unclickable links on my first attempt ;-)

Also implemented other comments from Jan. I think this is good to go and replace the timeline on the history page, so - I'm going to make that happen in the next commit. You can preview the current state still on https://staging.owncloud.org/timeline

**Comment by jospoortvliet** [comment]
@jancborchardt @karlitschek

**Comment by jospoortvliet** [comment]
Now that is done too. Merging to Master so we can review it...

**Comment by jospoortvliet** [comment]
See on https://staging.owncloud.org/history/ (in a few minutes)

**Comment by jancborchardt** [comment]
Nice! But again about the screenshot of 1.2 in the 1.1 entry: Either remove it there, or put it correctly in the timeline. ;) No one will read »this is 1.2 actually, we have no screenshot of 1.1« – folks only look at images ;)

* remove the screenshot there – we need to take one of 1.1 (if it’s much changed from 1.0)
* create another entry for the 1.2 release when it was released (don’t remember the date – was it actually after the first meeting?) and put the 1.2 screenshot there.

**Comment by jancborchardt** [comment]
Also, the »ownCloud Android and iOS apps launched« is a bit incorrect. I would call it »relaunched« since there was an Android app from the community quite some time before that.

See https://github.com/owncloud/android-legacy/commits/master – April 2012 and I think it existed before that as well. Unfortunately the commit history isn’t there.

**Comment by jancborchardt** [comment]
And as well: Do we have no pictures of the dev meetings from October 2011, August 2012 or February 2013? There’s a blog post with pictures about the April 2012 one: http://karlitschek.de/2012/04/what-a-weekend/ and we should take a pic from there.
Every dev meeting event should have a picture embedded, so the homies are shown and the growth is visible. : )

**Comment by jancborchardt** [comment]
And the October 2012 sprint seems to be missing? It had a simultaneous sprint with 4 participants or so in Ann Arbor. (See blogpost http://karlitschek.de/2012/09/worldwide-owncloud-developer-meeting-in-october/), I think @cosenal also attended there and might have the photo – I know there was one. :D

**Comment by jancborchardt** [comment]
Tiny possible enhancement: For the entries »New office in X« – add an image of the office. :)

(Sorry for putting all my enhancement requests in here …)

**Comment by cosenal** [comment]
Here is a blogpost (with pictures) by Michael and myself about that meeting: http://blog.gapinthecloud.com/2012/11/08/great-lakes-owncloud-developer-meetup/

(That timeline looks so cool!)

**Comment by jospoortvliet** [comment]
thanks a lot for the links - believe me, I searched all over ;-)

I'll implement this tomorrow. Then it can go live with the next deployment.

@cosenal thanks, I've put way to much time and effort in it but it was fun to do, I learned a lot and the result is very satisfying ;-)

**Comment by jospoortvliet** [comment]
The changes are made, see  #693 
Yes, there are still meetings and releases without pictures - simply because I couldn't find the right pic. Hints still welcome.

I'll whip up a quick blog post about our history page, OK?

**Comment by jospoortvliet** [comment]
@jancborchardt wish I had pics of the offices but... S3 is down again. Sigh. Later, Ok, going to ask for deploying this later today.

**Comment by jancborchardt** [comment]
@jospoortvliet the 1.2 release should of course come _after_ the developer meetup, as it was released at the end of it. ;)

**Comment by jospoortvliet** [comment]
@jancborchardt pfff... details... It's both in the same month. But ok, I'll add it to my list ;-)

**Comment by jancborchardt** [comment]
Right, I guess similar to how Neil Armstrong stepped on the moon, and then some time later Apollo 11 started from earth. Cause it was in the same month. ;D

**Comment by jospoortvliet** [comment]
Actually if you read from top to bottom I 'fixed' it in the wrong direction now.

Perhaps if you look at Armstrong coming at you from the moon... In an alternate universe where time flows backwards... 

/me hides

**Pull request merged**
