### PR TITLE
Point bugtracker url from core to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by RealRancor**
Fixes https://github.com/owncloud/owncloud.org/issues/859

### CODE REVIEW

**Comment by RealRancor** [comment]
An alternative could be:

https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by karlitschek** [comment]
Great idea. This link is old. But actually we should point people to this page: https://owncloud.org/support/  :-)

**Comment by RealRancor** [comment]
@karlitschek That is the page where i'm changing this link. :-)

**Comment by karlitschek** [comment]
Yes. This was a complete BS comment from me ;-)

**Comment by karlitschek** [comment]
I vote for this link :-) https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by RealRancor** [comment]
@karlitschek Yes, i also think that one is better. Then we also don't need to change the version number to the docs at that page.

**Comment by karlitschek** [comment]
:+1:

**Comment by RealRancor** [comment]
@PVince81 @LukasReschke @MorrisJobke Any other opinions?

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@jospoortvliet Could you please merge and deploy this? Or @danimo

**Pull request merged**
