### PR TITLE
new frontpage design, yaya!

### PR DESCRIPTION
**Pull request by jospoortvliet**

### CODE REVIEW

**Comment by enoch85** [comment]
Great work! Just one small "bug":

image

In Chrome (on Ubuntu Mate) you can't see the text. Shouldn't this be white instead?

**Comment by jancborchardt** [comment]
@enoch85 caching issue maybe? Try an incognito window or Ctrl-Shift-R refreshing?

**Comment by jospoortvliet** [comment]
@enoch85 can you re-check? It works on every browser I have access too - A bunch of webkits: chrome, chromium, reKonq and Konqueror as well as KHTML (webKit predecessor) and Firefox. Works on my android phone, too.

**Comment by LukasReschke** [comment]
I had this as well. It was caching related and I had to clear my cache manually. We probably need some kind of cache buster or so on.

**Comment by enoch85** [comment]
@jancborchardt Yes, caching issue indeed. CTRL+F5 solved it.

**Comment by jospoortvliet** [comment]
Ok.

**Pull request merged**
