### PR TITLE
update live

### PR DESCRIPTION
**Pull request by jospoortvliet**
Bunch of changes and improvements to the website:
New trademark page, federation page, updates to event page, improvements to support and promote pages.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
all tested on staging.

**Comment by carlaschroder** [comment]
You tested this?

;)

**Comment by carlaschroder** [comment]
Kidding, you're doing great work with the site. It looks really good and it's easy to find stuff.

**Comment by jospoortvliet** [comment]
@carlaschroder thanks ;-)

Now waiting for deployment... Will kick sysadmin agian D:

**Pull request merged**
