### PR TITLE
Finish owncloud.org/eight

### PR DESCRIPTION
**Pull request by jospoortvliet**
More changes coming.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
@LukasReschke at your service: added screenshot. If we don't get a vid, this'll do.

**Comment by MorrisJobke** [comment]
@jospoortvliet Shouldn't this go against the stable8.0 branch as @tomneedham pointed out?

**Comment by jospoortvliet** [comment]
@MorrisJobke on the Database - I would need a screenshot of that, I don't have this myself. On the branch - no clue... Don't we always go against master? I am clueless, officially :dancer: 
Besides, I'd like to get this live... If there's nothing badly wrong, that is.

**Comment by tomneedham** [comment]
Now checking this out :)

**Comment by tomneedham** [comment]
@jospoortvliet Checkout skype :)

**Pull request merged**
