### PR TITLE
ownCloud Eight features page

### PR DESCRIPTION
**Pull request by jospoortvliet**
@karlitschek @tomneedham and whoever else is interested... First draft of owncloud.org/eight ;-)

Rather than owncloud.org/seven I took the design of owncloud.org/features as @jancborchardt has been complaining about the look of that page.

Feedback on both text as well as design welcome. I'm waiting for feedback on the announcement draft, from which much of this text is taken, so that will bring some changes still. Just wanted to get this first draft out there.

Screenshot below (on 1080x1920 thus 90⁰ rotated screen):
eight

### CODE REVIEW

**Comment by karlitschek** [comment]
you are fast! :+1:

**Comment by jospoortvliet** [comment]
Look is still largely the same. If @MorrisJobke and @jancborchardt are OK with it it looking this way, I think it can go to staging already...

**Comment by MorrisJobke** [comment]
Can we also added some bug fixing topics? Maybe something like "more robust external storage for webdav and SMB" or maybe @pvince84 knows some nice improvements there, that were problems in 7 but are fixed in 8, because otherwise it will again look like a complete feature-only release. Bug fixes and robustness are also essential features that can be promoted as well (if they are actually true ;))

**Comment by LukasReschke** [comment]
@PVince81 just got younger! ;-)

**Comment by MorrisJobke** [comment]
@PVince81 ;) (it didn't autocomplete anymore vincent :()

**Comment by MorrisJobke** [comment]
:cry:

**Comment by PVince81** [comment]
A few that come to mind:
- mounting ownCloud into ownCloud as external storage now work properly with encryption
- improved group share handling (when sharing a file multiple times with the same user over group+user) not 100% sure CC @schiesbn (might have been backported stuff)
- encryption keys are now stored in folders which makes it easier/faster to move (more efficient code)
- small performance improvement by caching encryption keys that are reused multiple times within a single PHP request

Hmm... I quickly browsed through the list of closed tickets and commits but didn't find that many that are interesting to expose. Also many were backported to OC 7.

**Comment by MorrisJobke** [comment]
@PVince81 Thanks. I just had you in mind, because you had done a lot "under the hood". ;) I guess this is enough for a smal teaser text and a new category of improvements, @jospoortvliet ;)

**Comment by PVince81** [comment]
So much has happened, hard to remember.

One idea would be to have a "Changelog" wiki page where people can add whichever bigger fixes were closed, and do this as soon as the fix was closed, not several months later.
Not sure how @karlitschek usually proceeded to create changelogs so far ?

**Comment by MorrisJobke** [comment]
@PVince81 You're right. Maybe we can add this to the workflow. Once anything relevant is merged the author has to write it to the changelog wiki page.

**Comment by LukasReschke** [comment]
Well, we could do stuff automated if people could agree on one standard for commit messages :) https://pypi.python.org/pypi/gitchangelog/2.2.0

**Comment by MorrisJobke** [comment]
@LukasReschke That doesn't work, because otherwise the commit head is full of qualifiers which component is effected :( And there are always people that didn't add proper commit messages :cry:

**Comment by jancborchardt** [comment]
> Rather than owncloud.org/seven I took the design of owncloud.org/features as @jancborchardt has been complaining about the look of that page.

@jospoortvliet thank you very much! Looks great! :) Only one thing: Can we please call the versions by numbers, that is owncloud.org/8 instead of writing them out as »Eight«? That just looks strange.

**Comment by MorrisJobke** [comment]
Then we need to call it 8.0, because 8.1 is no subset of 8 but a new major version.

**Comment by jospoortvliet** [comment]
FYI - am working on incorporating the comments ;-)

**Comment by karlitschek** [comment]
@PVince81 We don´t do changelogs for major version but only minor versions.

**Comment by jospoortvliet** [comment]
@MorrisJobke @jancborchardt ok, owncloud.org/8.0 it will be with the next commit.

@PVince81 look at the last item in the admin section - improvements and polish all over is what is claimed. I know there's quite some good performance and bugfix work (isn't there always?) and I'd love to talk it up as a feature but as mentioned, most is back ported to stable 7...

I have used @MTRichards text for it all, he wrote it more value-based and less concrete. We can debate if it should be more concrete but that's a conversation that should include him :D

**Comment by jospoortvliet** [comment]
actually, it has to be 8-0, not 8.0 due to a limitation in Wordpress (from what I can tell)...

**Comment by jancborchardt** [comment]
Please don’t make it 8.0 / 8-0 :D that’s just technical details. owncloud.org/8 is much simpler, and that page will simply evolve over time if need be.

**Comment by MorrisJobke** [comment]
> Please don’t make it 8.0 / 8-0 :D that’s just technical details. owncloud.org/8 is much simpler, and that page will simply evolve over time if need be.

But then people expect that 8.1 is just a minor release, but it is a major one :( Let's see

**Comment by jancborchardt** [comment]
Yeah … so then we touch the problem with how we name versions. ;) I would rather have the URL stay owncloud.org/8, and then adjust the content of the page for 8.1, 8.2, 8.3

Don’t have a particular preference on this though. I just think the URL owncloud.org/8.0 or 8-0 is really ugly and techy.

**Comment by jospoortvliet** [comment]
Let's make it 8...

**Comment by jospoortvliet** [comment]
so that doesn't work in wordpress. @jancborchardt @LukasReschke @MorrisJobke it is either 8-0 or eight, I can't do 8.0 or 8 0 or 8. Choose... For now, i go with eight as that fits with what we did before.

**Comment by jospoortvliet** [comment]
I'd like to move this to staging to be able to get some actual review on the text...

**Comment by jospoortvliet** [comment]
So I'm being a dick and merge my own stuff.

**Comment by jospoortvliet** [comment]
Will make a new PR for further changes.

**Comment by jancborchardt** [comment]
Yeah, works for me. Why does »8« not work with wordpress? Minimum character limit or what?

**Comment by jospoortvliet** [comment]
@jancborchardt yeah, something like that I suppose. I tried it locally and on our server and whatever I tried, a number (no matter how many digits) would always get a -0 (or -1 or -2) attached. Guess it's a wordpress thingy...

**Comment by jospoortvliet** [comment]
You can now see the state on http://staging.owncloud.org/eight/ - @jancborchardt @MorrisJobke any further feedback is welcome :D

**Comment by MorrisJobke** [comment]
I will propose some updated pictures ;)

**Comment by MorrisJobke** [comment]
@jospoortvliet I just shared to an external cloud and then right clicked the text and "inspect element" then you can change the text and don't have to put that ugly distortion filter onto it ;) (I have no nice data to be presented in the picture)
bildschirmfoto von 2015-01-29 14-41-03

**Comment by MorrisJobke** [comment]
I think that is better than this:
bildschirmfoto von 2015-01-29 14 44 04

**Comment by LukasReschke** [comment]
:+1: * :100:

**Comment by MorrisJobke** [comment]
Also the User_LDAP has proper names ;)

**Comment by MorrisJobke** [comment]
Let me create a screenshot for that

**Comment by MorrisJobke** [comment]
@jospoortvliet Just use that one:
user-management

**Comment by tomneedham** [comment]
@jospoortvliet I believe >8< for the page url should be fine. Wordpress will auto change it, if you ahve another page with this name in your instance so this might be the issue.

**Comment by tomneedham** [comment]
@MorrisJobke We have: https://github.com/owncloud/screenshots/tree/stable8.0

**Comment by MorrisJobke** [comment]
https://cloud.morrisjobke.de/public.php?service=files&t=a9502fd4b25b86e36af3e3e71cf33094

**Comment by MorrisJobke** [comment]
I will create a PR to include these images

**Comment by MorrisJobke** [comment]
@jospoortvliet takes care of this :dancers:

**Comment by jospoortvliet** [comment]
All in the other PR: #411

**Pull request merged**
