### PR TITLE
Added links to old sync-client versions

### PR DESCRIPTION
**Pull request by RealRancor**
Fixes: #395

### CODE REVIEW

**Comment by RealRancor** [comment]
Seems older clients like 1.5.3 of https://github.com/owncloud/owncloud.org/commit/3718a9ffcc22ad5989f480a868a6920d75070bb7#diff-505deb1f24c67951328ff321e3895d8bL20 are not available anymore.

**Comment by danimo** [comment]
I don't really like the idea of providing older versions, especially so long into the past. They have known bugs and we regulary get bug reports from people using old versions that have long been fixed.

**Comment by RealRancor** [comment]
Hi,

i agree with you but its an often asked question at the forums.

Especially in the case of the dropped support of Mac OS X 10.6 with the client 1.6.0 or after an major release of the client which breaks stuff not seen in older versions.

**Comment by danimo** [comment]
That is exactly the point: We no longer support 10.6, just as apple. And clients still supporting it are really buggy. We are doing those people a disservice really.

**Comment by RealRancor** [comment]
Also understandable. But especially in the case of Mac OS X the people needs to throw away their hardware to be able to upgrade to a newer OS or am i wrong?

**Comment by danimo** [comment]
Yes, tough luck. If you buy Apple, you live with their rules, or at least replace OS X with Linux. I know that people will always say that this is not an option for them, but this cannot be our concern. Our concern must be to provide the best possible experience for _vendor supported_ OSes. And old bug reports have gotten in the way of that far too often :(

**Comment by jospoortvliet** [comment]
I'm agreeing with Danimo here... I think we're not helping anyone by allowing them to run a buggy, broken version of our software....

**Comment by dragotin** [comment]
No, 1.6.0 is NO option. Sorry.

**Comment by danimo** [comment]
Proposal: Let's limit this to the last version. This is legitimate as there may be problems in the latest version. I see no valid use case that we want to support other than that.

**Comment by RealRancor** [comment]
Yes, that could be a good idea as at least one previous major version should be provided. Will change the PR later.

**Comment by karlitschek** [comment]
yes. this is how we do it on the server too. We should link to the latest patch releases but not to version that have known bugs.

**Comment by RealRancor** [comment]
For server all packages are provided at:

https://owncloud.org/changelog/

Even 3.0 is available there.

**Comment by dragotin** [comment]
Yeah, 3.0 is listed, but the tarball gives a 404

**Comment by RealRancor** [comment]
Ok, changed the PR to only list 1.8.0, 1.7.1 and 1.7.0

@dragotin 

Ok, then let me choose 6.0.1 which was requested to be removed from the Ubuntu package because it contains tons of vulnerabilities:

https://download.owncloud.org/community/owncloud-6.0.1.tar.bz2

Not talking about all the 4.5.x and 4.0.x releases still available. 3.0 was probably the worst example :-)

**Comment by jospoortvliet** [comment]
:+1: 
@dragotin you good with this?

**Comment by dragotin** [comment]
@well, @RealRancor is the guy who knows the community ramblings, so who am I to object him? Sure, go ahead!

**Pull request merged**
