### PR TITLE
new advisories

### PR DESCRIPTION
**Pull request by Peter-Prochaska**
created some new advisories

### CODE REVIEW

**Comment by PVince81** [comment]
Looks fine :+1: 

@crrodriguez @jnweiger deploy ?

**Comment by RealRancor** [comment]
@PVince81 @Peter-Prochaska Seems the "SMB User Authentication Bypass" got missed as the "oC-SA-2016-016" linked there is a advisory for the Desktop Client.

**Comment by PVince81** [comment]
@Peter-Prochaska indeed, https://owncloud.org/security/advisory?id=oc-sa-2016-016 points to an older advisory. Can you adjust ?

**Comment by DeepDiver1975** [comment]
2016-016 already exists in desktop - my fault actually when passing over the information on how to do advisories ..... :see_no_evil: 

https://github.com/owncloud/security-advisories/blob/master/desktop/oc-sa-2016-016.json

**Pull request merged**
