### PR TITLE
add tech and me from en0ch

### PR DESCRIPTION
**Pull request by jospoortvliet**
@enoch85 here you go ;-)

### CODE REVIEW

**Comment by enoch85** [comment]
Thanks! :+1

**Comment by enoch85** [comment]
Same rules apply here with the :+1: ? In that case, please review @owncloud/designers

**Comment by jancborchardt** [comment]
This is not really something to cc the design team on. ;)

**Comment by jospoortvliet** [comment]
hehe

I think this can go in.

**Comment by jospoortvliet** [comment]
But there is something I'd like to hear thoughts from @LukasReschke and @danimo on:

guys, while I think this is OK (we know Daniel after all and he's been around for a while), how open should we be to adding to this page? After all - anybody could make an ownCloud VM - but they can go unmaintained easily and, worse perhaps, be abused for all kinds of nefarious stuff... Where do we draw the line?

Right now, we have:

# SUSE Studio image
Done by Cornelius Schumacher, known to many of us personally (and for a bloody long time), been updating his image for years

# Bitnami
Company doing this, we have a business relationship with them (well... we're talking, at least). They've been on this for a while, too.

# Ubuntu Juju
I've met the guy and talked to some community folks at Canonical, they are very much interested in keeping this going and have been maintaining it for quite a while, too.

# Tech and Me/Daniel
And now this image, done by Daniel. He's been around in ownCloud for a while but this is quite new and there is no team effort/backing here atm.

@enoch85 don't take this the wrong way, but you are, of these four, the one I'm most unsure about ;-)

Question is: what guidelines should I follow in adding things to this page? A quick and dirty proposal (not saying the current 4 satisfy these):

* Has to be 'alive' for at least 3 months with a consistent and prompt update policy (every minor update applied within 2 weeks)
* Has to have a 'personal connection' to ownCloud - at least one core contributor or ownCloud, Inc. employee is willing to vouch for the person(s) behind the effort due to knowing him/her/them

What do you think?

**Comment by enoch85** [comment]
@jospoortvliet and all the others. As you all know my aim is to spread the word about ownCloud. More than 50% of my website (https://www.en0ch.se) is about ownCloud and tips & trick regarding ownCloud. As I stated on Twitter I will update the VM, and improve scripts and such every 0.1 realease. The day that (even if it's not likely to happen) I don't provide updates anymore I will of course let you know.

I don't need a team that backs me, I do everything by myself. ;) And it's in my own intrest to keep my image updated because if I don't you would'nt link it.

I think the alternatives that are presented on the page is good, but my aim is to make it as simple as possible. Therefore I have made the VM as I would want it myself, with the documents app pre-configured as an example and also with the secure_owncloud.sh script. After all, Ubuntu and Apache with MySQL is very common around ownCloud users, and if I can help very novice users to get ownCloud instead, that's just a big +. #Dropdropbox (!)

I have got great response from different downloaders around the world, and I get sevreal emails per week - thanking me for such an easy install.

Please test it yourself, and also look throug my website, I garantuee you will be satisfided. ;)

**Pull request merged**
