### PR TITLE
first conf info page

### PR DESCRIPTION
**Pull request by jospoortvliet**
@jancborchardt @blizzz @karlitschek a page with some basic conference information.

We should put a link to this (owncloud.org/conf/confinfo) in some places so ppl can find it easily... On posters perhaps.

I've designated room MA642 the `starter room` - the place where you go if you have questions, are looking for somebody or don't know where to get started.

Ppl in that room are there to hack, but also to answer questions of any kind.
conference information - owncloud website

What do you think? What's missing?

### CODE REVIEW

**Comment by karlitschek** [comment]
Awesome. A lot better then last year :+1:  :-)

**Comment by jancborchardt** [comment]
Nice, thanks for acting on my suggestion @jospoortvliet ;)

Just a few typos:
* **Straße** des 17. Juni instead of Strasse
* after 18:00 and **on** the weekend
* many rooms are **equipped**
* answers about **APIs** without apostrophe
* ask your questions in **the** starters room
* use »*Mathematik*« style quotes instead of "*Mathematik*" ones

Also, use Open Sans and unbold the headings (just a bit bigger, not bold).

**Comment by blizzz** [comment]
@jospoortvliet awesome. That looks pretty round. What you might want to add:

Add "Ernst-Reuter-Platz (U)" and "Tiergarten (S)" as closest public transport stops. And/Or provide this wonderful [BVG link](http://fahrinfo.bvg.de/Fahrinfo/bin/query.bin/en?pk_campaign=BVG.de_Eingabe&from=&REQ0JourneyStopsS0ID=&REQ0JourneyStopsfromID=&REQ0JourneyStopsSA1=7&HWAI%3DJS!js=yes&HWAI%3DJS!ajax=yes&to=+10623+Berlin-Charlottenburg%2C+Str.+des+17.+Juni+136&REQ0JourneyStopsZ0ID=&REQ0JourneyStopstoID=A%3D2%40O%3D10623+Berlin-Charlottenburg%2C+Str.+des+17.+Juni+136%40X%3D13326247%40Y%3D52513247%40U%3D103%40L%3D7706964%40B%3D1%40p%3D1431509568%40&REQ0JourneyStopsZA1=7&date=27.08.2015&time=09%3A00&timesel=arrive&start=1) so people can easily find their way to the conf. 

Add "ground floor" when talking about conference and workshop rooms.

Although it should be clear, maybe note that people bring power adapters if they are coming from abroad and are not compatible with German standard.

**Comment by jospoortvliet** [comment]
Ok let's just get this to staging...

**Pull request merged**
