### PR TITLE
improve style following MorrisJobke's request

### PR DESCRIPTION
**Pull request by jospoortvliet**
@danimo sorry, one more...

### CODE REVIEW

**Comment by jospoortvliet** [comment]
wait a sec

**Comment by jospoortvliet** [comment]
Ok... Good to go.

**Comment by jospoortvliet** [comment]
eight1

**Comment by MorrisJobke** [comment]
:+1:

**Comment by danimo** [comment]
active on staging and live.

**Comment by jospoortvliet** [comment]
@danimo you rock!

**Pull request merged**
