### PR TITLE
History

### PR DESCRIPTION
**Pull request by jospoortvliet**
Let's continue #680 here.

It currently isn't on https://staging.owncloud.org/timeline because the auto-deploy of master to there is broken. I notified sysadmin.

Current look is as https://github.com/owncloud/owncloud.org/pull/680#issuecomment-140157891

I'd like to hear if this is the direction we want to take it before I start adding the rest. @jancborchardt @karlitschek

### CODE REVIEW

**Comment by karlitschek** [comment]
I like this a lot. Very beautiful. But please don't spend too much time here. This is already a ton better then what I expected. :-)

**Comment by jancborchardt** [comment]
Yeah, totally fine: Publish it and let’s go! :)

**Comment by jospoortvliet** [comment]
I have one serious issue, which was also pointed out by @LukasReschke - some of the links are unclick-able. I think this has to do with some invisible overlap or z-height issues, due to the positioning - which is a bit complicated because the items partially overlap left/right.

I am honestly entirely unable to fix this - I don't even know where to start. Actually, I feel pretty smart about thinking it has to do with z-height as I didn't even know what that was 3 days ago :smiling_imp:

**Comment by jospoortvliet** [comment]
But let me merge this and then we can fix that problem in another PR. At least you can see for yourself on staging ;-)

**Comment by jancborchardt** [comment]
@jospoortvliet I assume /timeline will just become part of /history and not be its own thing, right? Cause duplicating it makes no sense.

**Comment by jancborchardt** [comment]
@jospoortvliet the screenshot of »ownCloud 1.1 launched« at https://staging.owncloud.org/timeline/ is either 1.2 instead of 1.1, or it’s wrong in the timeline. It already has the icons and stuff I made at the first hack event. ;)

**Comment by jospoortvliet** [comment]
@jancborchardt yes, I'll remove timeline, it is just for the staging server while we get this working. I will replace the timeline on the history page once we're done.

About the pic - will fix it, linking to https://dot.kde.org/2011/04/21/first-owncloud-sprint - adding 1.2 etc etc. Thanks!

**Pull request merged**
