### PR TITLE
add business event banner

### PR DESCRIPTION
**Pull request by jospoortvliet**
What it looks like at various sizes:
Big/fullHD and up:
event button
Small, around 1280x720 or so (tablets...)
event button1
About landscape phone:
event button2
Portrait phone:
event button3

The link is clickable.

This is done in a reasonably generic way, in the sense that we can replace this banner with a similar image at the same size for future events/stuff we want to promote, like releases, conference etc.

Reviewed by @jancborchardt but more input from him and others welcome!

### CODE REVIEW

**Comment by jancborchardt** [comment]
It’s fine everywhere except the tablet size (2nd screen), it should also be placed below the button. And it seems to be a bit big, no?

And on the third, maybe move it a bit down?

**Comment by jospoortvliet** [comment]
@jancborchardt it is bigger on the 2nd as the total screen is smaller - I want to ensure it is readable. It doesn't fit across that entire range below the button - it overlaps a bit, so I had to move it away. You see in the third pic how close it is. And yes, I can move that down a bit, will do. But I'd like not to do that also in tablet mode, that looks meh...

On it. New screenshot coming.

**Comment by jancborchardt** [comment]
Ok – works for me then.

**Comment by jospoortvliet** [comment]
event button5
feedback from jan and Snezana incorporated.

**Comment by jospoortvliet** [comment]
silence is yes. Going live ;-)

we can fix it further later on.

**Comment by jancborchardt** [comment]
Ey, top left is the worst choice! :D Why did you completely move it around? It was fine below the button. Now it fights with both the ownCloud logo _and_ the button, and always takes precedence cause it’s so present.

**Pull request merged**
