### PR TITLE
Upgrade to FontAwesome 4.5.0

### PR DESCRIPTION
**Pull request by tomneedham**
@jospoortvliet Please check for any explosions ;)

### CODE REVIEW

**Comment by tomneedham** [comment]
I tested that some FA 4.5.0 icons worked.

**Comment by jospoortvliet** [comment]
better test on staging ;-)

**Comment by jospoortvliet** [comment]
snapshot_j14286

bug! ;-)

Not sure why that doesn't work anymore... Everything else looks good here, tried pages like staging.owncloud.org/support staging.owncloud.org/contribute staging.owncloud.org/eight-two and so on.

**Comment by jospoortvliet** [comment]
found and fixed it by converting text to path in that icon. https://github.com/owncloud/owncloud.org/commit/e3158b5eb94e7fe9c7c5099f83b5c7d04ed8a33d

**Comment by tomneedham** [comment]
oh nice job!!

**Pull request merged**
