### PR TITLE
History

### PR DESCRIPTION
**Pull request by jospoortvliet**
Added a nice time line with ownCloud events from the last 5 years to our history page. A few minor gaps and issues, feedback super welcome! @karlitschek @jancborchardt and everybody else ;-)

All icons are svg and somehow - that creates problems. Some are cut off, especially the shadows don't look good. As svg is more scalable it'd be nice to keep it svg instead of png but then I need some ideas on how to deal with the cutting off...

Here's a full picture of the page. 
history - owncloud website

### CODE REVIEW

**Comment by jancborchardt** [comment]
The headings should be above the events of that year, not below. ;)

Also to make it a bit more visual and to show the incredible growth, I would add a picture of each of the dev meetings from 2011 all the way to the conf 2015.

**Comment by jancborchardt** [comment]
Btw, the second developer meeting was in Zurich, on the weekend of October 22–23. It was hosted by https://github.com/FreeMinded and consisted of 7 people – the 5 from the first meeting plus Pascal and a friend/colleague of his.

(I know the date cause after that [I gave a talk at JSZurich](http://techup.ch/403/jszurich-unhosted-freedom-from-the-web-s-monopolies-you-provide-the-app-your-users-have-their-data-where-they-want) ;)

**Comment by jospoortvliet** [comment]
@jancborchardt awesome, will make the changes. A question: do you happen to like this look more:

timeline - owncloud website

It would be a bit of work to make it all look like that (I only did 2015 now) but if you think it's worth it, I am up for it. @camilasan I did it!!! ;-)

**Comment by jospoortvliet** [comment]
shit1
@jancborchardt that's how images would look

**Comment by jancborchardt** [comment]
It would be a better layout, but only if the respective other side (in this case the left side when the image is on the right) doesn’t have that much whitespace, but rather the events below move up.

**Comment by jospoortvliet** [comment]
@jancborchardt ok, that is not easy. I made it work but it is quite a bit of manual work. Did manage to make it responsive, though. Now we'll have to figure out what to give images to - the left vs right and the extra spacing I have to do manually. Do we want screenshots and youtube videos of releases, too? Pictures of office? I can add a shitload of images, would make it nicer...

Want me to?

**Comment by jospoortvliet** [comment]
The updated look
timeline - owncloud website 1

**Comment by karlitschek** [comment]
looks good. :+1: 
As you know I'm a big fan of starting with something and improve over time. :-) 
Sheryl Sandberg: 'Done is better than perfect.'

**Comment by jospoortvliet** [comment]
Ok, then, let's first merge the history page as it is in https://github.com/owncloud/owncloud.org/pull/680#issue-106168286 and improve after that ;-)

**Comment by jospoortvliet** [comment]
(don't delete the branch, I'll continue here)

**Comment by jospoortvliet** [comment]
timeline - owncloud website 2
@karlitschek @jancborchardt too many images/videos, or nice?

**Pull request merged**
