### PR TITLE
Add a ownCloud-5-years page with quotes

### PR DESCRIPTION
**Pull request by jospoortvliet**
Let's get this live fast pls...

### CODE REVIEW

**Comment by jospoortvliet** [comment]
@tomneedham @danimo this PR is good with one issue: I wanted the look of the conference site but I couldn't figure out how to get that CSS file to apply to the page page-5years.php so I developed the page as replacement for owncloud.org/conf and then copied it, once done, to page-5years.php and will rely on help from either of you to actually have it look properly... See screenshot.

screenshot

Any chance you can help me get this merged and live before Monday lunch time (Europe)?

Thanks in advance :D

**Comment by tomneedham** [comment]
@jospoortvliet This looks great, I will have a chance to sort this tomorrow evening. IIRC, the conf page has a separate stylesheet, which is included when certain pages are loaded. See https://github.com/owncloud/owncloud.org/blob/master/templates/head.php#L16

**Comment by karlitschek** [comment]
:+1:

**Comment by tomneedham** [comment]
I don't think this is actually working right now, right @jospoortvliet ? We still need to update the css loading and I can checkout the code tomorrow.

**Comment by LukasReschke** [comment]
CSS is fixed at https://github.com/owncloud/owncloud.org/pull/405

See http://staging.owncloud.org/5years/

**Comment by LukasReschke** [comment]
(though not sure if the "ownCube TBD" is really what we want to have written there :D)

**Comment by jospoortvliet** [comment]
@LukasReschke yeah, that still has to be fixed. If they haven't send something in until Monday morning, I replace it with something else.

@tomneedham took me a while to find it, @camilasan helped :dancers:

**Pull request merged**
