### PR TITLE
improve social media pics on promote page

### PR DESCRIPTION
**Pull request by jospoortvliet**

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by karlitschek** [comment]
:+1:

**Comment by LukasReschke** [comment]
5.0.19 got released as well? – Also 5-7 releases contain security patches.

**Comment by jospoortvliet** [comment]
will add 5.0.19

**Comment by jospoortvliet** [comment]
Done. @karlitschek let's get this live :dancers:

**Comment by LukasReschke** [comment]
Please add "Several security fixes. (Will be disclosed 2 weeks after the release)" (or so) to 5-7, but not to 8.0.2. THX :)

**Comment by jospoortvliet** [comment]
@LukasReschke ok

**Comment by jospoortvliet** [comment]
@LukasReschke done. can you check?

**Comment by LukasReschke** [comment]
:+1:

**Pull request merged**
