### PR TITLE
link to dev docu about processes

### PR DESCRIPTION
**Pull request by jospoortvliet**
Linking to our development and decision making processes - inspired by https://github.com/owncloud/owncloud.org/issues/626

### CODE REVIEW

**Comment by jospoortvliet** [comment]
@LukasReschke @RealRancor any more suggestions?

**Comment by LukasReschke** [comment]
Looks good. Can't judge if the link will work :speak_no_evil:

**Comment by jospoortvliet** [comment]
It will but you can test on stable as soon as this is merged ;-)

**Comment by jospoortvliet** [comment]
and by Zeus, github should really support dead standard smileys... :D :-) :) ;)

**Comment by RealRancor** [comment]
Sorry, i don't have any insight in the development and decision making processes so can't say something if this could be useful here.

**Comment by jospoortvliet** [comment]
ok, let's at least add this - other ideas are still welcome.

**Pull request merged**
