### PR TITLE
some fixes to timeline

### PR DESCRIPTION
**Pull request by jospoortvliet**
fixes from JFD and dvelasco

### CODE REVIEW

**Comment by butonic** [comment]
:+1:

**Comment by butonic** [comment]
@jospoortvliet um ... so what is the policy here? two :+1: or ... ? doas this automagically get deployed to owncloud.org?

**Comment by butonic** [comment]
nevermind ... just read the README :blush:

**Comment by jospoortvliet** [comment]
No more comments have come in so let's merge this.

**Pull request merged**
