### PR TITLE
Replace portknox logo

### PR DESCRIPTION
**Pull request by Gomez**
As animated GIF

### CODE REVIEW

**Comment by jancborchardt** [comment]
Not sure we wanna allow gifs here. ;) Otherwise it’ll go crazy sooner or later. @tomneedham @jospoortvliet

**Comment by tomneedham** [comment]
@jancborchardt This is true. I believe we have one already so a decision needs to be made. Shall get this clarified in our new provider guidelines: https://github.com/owncloud/owncloud.org/commit/530c9989aa99ded1f74efa167a6aeb94f1f46806

**Comment by jancborchardt** [comment]
Decision: We do not allow animated GIFs. :) (or APNGs for that matter …)

**Comment by tomneedham** [comment]
:)

**Comment by tomneedham** [comment]
Sorry @Gomez !

**Pull request closed without merging**
