### PR TITLE
Add Blackberry app

### PR DESCRIPTION
**Pull request by jospoortvliet**
statistics april 20 2017

### CODE REVIEW

**Comment by karlitschek** [comment]
nice :+1:

**Comment by jancborchardt** [comment]
Ooh I’d love it as soon as we can put »Available on the Firefox Marketplace« there. :) cc @cosenal @Apophenia

**Comment by cosenal** [comment]
@jancborchardt Let me finish my thesis (two months left). After that, I will work on shipping the FxOS app ;-)

**Comment by jancborchardt** [comment]
@cosenal I’ll happily help (I have a FxOS phone again ;) – let’s definitely do some hacking at the ownCloud conf and before. :)

**Pull request merged**
