### PR TITLE
81release

### PR DESCRIPTION
**Pull request by jospoortvliet**
All the changes needed to be ready for ownCloud 8.1!

* 8.1 features page
* Release Channels page (and changes)
* Screenshots
* Updates to features, promote, install and changelog pages
* Press page (WIP)

### CODE REVIEW

**Comment by jospoortvliet** [comment]
The 8.1 features page has the same layout as last release so this just needs a content check and wording review, which can be done once it is moved to staging the days before the release.

I would like feedback from @karlitschek and @jancborchardt on the Release Channels page:
documents in 8 2

This is linked to from the install page (which I otherwise kept as it is):
documents in 8 2

and the changelog page:
documents in 8 2

Let me know what you think.

**Comment by jancborchardt** [comment]
@jospoortvliet the release channels should be sorted the other way around (production topmost, etc).

Also, we need to add Open Sans as typeface ;D #188

**Comment by jospoortvliet** [comment]
@jancborchardt will make the change.

No idea about how to do the typeface thing but I'm fine with it :D

**Comment by jospoortvliet** [comment]
I'm going to try and merge this to master for testing on staging. We're about one week from the release, so...

**Pull request merged**
