### PR TITLE
put youtube conf teaser videos on website

### PR DESCRIPTION
**Pull request by jospoortvliet**

### CODE REVIEW

**Comment by jospoortvliet** [comment]
statistics april 20 2017
statistics april 20 2017

What do you think @jancborchardt ?

**Comment by jospoortvliet** [comment]
Turns out that changing the thumbnail image makes the video fit in way better ;-)
statistics april 20 2017

statistics april 20 2017

**Comment by jospoortvliet** [comment]
@jancborchardt ok with this?

**Comment by jancborchardt** [comment]
On the conf subpage, the first thumbnail looks wayyyy better at least. But is it possible to use 2 different ones?

On the main page, we should also have a header for the video like »Join us at the ownCloud Contributor Conference« (oCC being linked to /conf)

And on the conf page, it should be theme=dark (or default) instead of light.

**Comment by jospoortvliet** [comment]
I can't have two different thumbnails, but I can fix the theme and add a header for the video.

**Comment by jancborchardt** [comment]
I’d prefer the first thumbnail then (just white logo over Brandenburg Gate). It also works ok for the main page if we have the header with link to /conf there.

@owncloud/designers what do you think?

**Comment by enoch85** [comment]
Go go go :)

**Comment by jospoortvliet** [comment]
ok, ok ;-)

**Pull request merged**
