### PR TITLE
bring EE link back

### PR DESCRIPTION
**Pull request by jospoortvliet**
@karlitschek @kelleybrooks
with mouse-over effect as shown here:
dev conversations 3

OK?

### CODE REVIEW

**Comment by kelleybrooks** [comment]
Works for me.  Thanks, Jos.

**Comment by jospoortvliet** [comment]
Now part of the whole website redesign.

**Comment by kelleybrooks** [comment]
why can't we put it back live now?  I think we've seen the impact and would love to reverse that as soon as possible?

**Comment by karlitschek** [comment]
I still hope that we can have the full new homepage ready really really soon. So we won't have an intermediate solution which is not optimal. Please give me 2-3 more days :-)

**Pull request closed without merging**
