### PR TITLE
Move provider list to popup.

### PR DESCRIPTION
**Pull request by jospoortvliet**
Move the full (and very long) list of providers to a popup, while three (?) most popular/chosen/best providers will remain visible.

Also on the agenda: creating a filtering for the Big List like done on https://owncloud.com/partner/

WIP!

### Choosing providers
It isn't clear yet what providers we want to have as the Chosen Three - suggestions on how to find out which ones are best would be welcome. I for sure don't feel like testing all of them ;-)

@karlitschek you had a list of some criteria - combined with my social media surveying we might have a start of a selection.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Current draft look of the page:

#### the Chosen Three
(which actually aren't there)
activity in owncloud1

##### The Popup with the rest
activity in owncloud1

**Comment by jospoortvliet** [comment]
@owncloud/designers feedback welcome. I have the problem that the list of providers is very long - should it scroll in the popup or should the page be very long?
(not that I know how to make the list in the popup scroll but I'm sure I can figure it out somehow)

**Comment by karlitschek** [comment]
works for me :+1:

**Comment by jancborchardt** [comment]
Wow, do we really want to do this? What’s the reason for it?

I mean, I sure do welcome it for less choice and better curation – but doesn’t that kinda say a big »fuck you« to our ecosystem?

**Comment by jospoortvliet** [comment]
@jancborchardt yes, it's a trade-off between convenience for users and love for our providers. Not an easy choice, but - if we really want to grow our user base, making it easier to pick a provider is important. Alternative suggestions are welcome!

A possible solution would be to have more than three 'chosen providers' and randomly display only three. But that requires some coding I can't do myself.

And the selection of properties and then showing only those that fit, as I mentioned, is another improvement - but that, too, is one I can't do myself. We'd need @tomneedham to dive in there. I have some example code from Achim but it sure ain't enough for me to do this.

**Comment by jancborchardt** [comment]
Ok – I agree that we should do this if we have transparent criteria of how you can be listed there. That way every provider can potentially achieve them if they are satisfactory. Otherwise people will be pissed that they are removed from a prime spot, and rightfully so.

Some criteria:
* age: the longer they exist, the more trustworthy they probably are
* version: only providers who run the latest stable version should show up
* contributes: a bonus for hosters who contribute back to ownCloud
* flexibility: supports both consumers and organizations
* free plan: I don’t want to make that too important since ppl have to earn money, but having a free plan is a pretty big deciding factor among file sync & share providers
* …

Then some criteria which are more subjective but also important:
* we know them personally in some way
* we haven’t heard of negative experience with that provider
* …

**Comment by jospoortvliet** [comment]
@karlitschek you had a list of criteria somewhere, too....

**Comment by tomneedham** [comment]
We have these, which are linked on the website somewhere: https://github.com/owncloud/owncloud.org/blob/master/assets/files/Provider_Guidelines.odt

**Comment by jospoortvliet** [comment]
@tomneedham yeah, but that's like the minimum they have to comply with. Doing that doesn't make them good and recommend-worthy... We'll have to pick three that are Real Good. If we can't choose between, say, 6 then we could do something with randomizing what three too show but I don't want to end up having a second set of criteria and providers bugging us about becoming part of that (they will probably, anyway...)

**Comment by karlitschek** [comment]
@jancborchardt looks fine. The only criteria i would add is overall user experience

**Comment by jospoortvliet** [comment]
So, after discussing all the criteria and how to define them and all that - an entirely different approach which doesn't create so much work:

How about we let the providers do our work for us.

As follows:

We email the providers and tell them we will run a survey. The results will control their sorting order on owncloud.org/providers, with the bottom half being delegated to a popup under a 'more providers' button (they won't want that...)

We set up a survey with just two questions measuring their NPS score:
* what is your current provider (drop down list)
* how likely is it that you would recommend this provider to a friend or colleague? (using a 0-10 scale)

The providers get a link and they get to send it to their customers.

We gather the results and use it to sort them. We re-run it once a year. No results (or very few) = bottom 50%, of course.

What do you think?

**Comment by jancborchardt** [comment]
That sounds like it will lead to a lot of fake ratings.

**Comment by jancborchardt** [comment]
I really think having a set of criteria, an objective rating system, is best. Where customer satisfaction / public image is one point of course.

Or we have some kind of bulletproof rating system. But I’m doubtful as I said.

**Comment by jospoortvliet** [comment]
Hmmm, ok, to avoid fake ratings, we might have to add some way of removing fakes or checking for it. Sigh.

Thing is - I dunno about you but I don't have time to check out all our providers and add lots of data about each of them. Who is going to check out (and sign up for half of them each time) after every release to see what version they run? Who's going to check when they started offering ownCloud? Who will check which ones we know? Sorry, but I'm not really feeling like that's a great use of my time. And we're already using plenty of Kait's time to check the newcomers. We might be able to add one or two things to her list of things to check but that's it.

And there are no 'objective criteria', even if the factor itself is rather clear it is still up to how much you value it.

Of course, we can add a limited number of other factors in the final score, besides customer satisfaction, but that one should imo be very important. The end user experience is most important in the end.

So, to limit the criteria to the most important and realistic-to-check:
* NPS (score *2 = points)
* free plans (+1 point)

That's what can be checked easily and seems relevant. As to your other thoughts:
* age: a lot of work to check and of minor importance imho. And bad for new ones - nonono, I wouldn't want to add this
* version: waaay to cumbersome to check. Who will do that?
* contributes: would be great but cumbersome to check. We could perhaps automate it, ask them to tell us a github account or multipe with which they contribute AND proof that these people work for them and then we can perhaps check with a script. But it will get outdated, people move jobs, do things in their free time... This is a PITA. (same issue with consultants page btw - there I really want to order on contributions but I fear it will become too complicated quickly).
* flexibility: supports both consumers and organizations -> I don't see the advantage, not at all.
* we know them: either you dig in each to make sure we don't miss any or it is totally arbitrary. Pff, no
* negative experiences: that is so ad-hoc and unfair I don't even get why you want to add that. If we can't verify it it makes no sense to take it into account. No offense.

**Comment by jancborchardt** [comment]
Ok, good points. Then let’s limit it to these:

* NPS (score *2 = points)
* free plans (+1 point)
* contributes (+1 point or more, this is easy to check and doesn’t change often)
* version (+1 point for current version, possibly negative points for outdated versions)

Version can be checked via the version.php or so and is similarly cumbersome as free plans. I do agree that the other points are less relevant, irrelevant, or even problematic.

**Comment by jospoortvliet** [comment]
Thing is, they tell us the free plans availability. We don't check it. Maybe once a year. The version thing would have to be checked every release for every provider. Unless you step up to do it, I won't be adding that, sorry.

**Comment by jancborchardt** [comment]
Ok, sounds good. However we should of course check the recommended 3 (or however many) regularly so we male sure they meet the requirements.

**Pull request closed without merging**
