### PR TITLE
create a 'consulting' page

### PR DESCRIPTION
**Pull request by jospoortvliet**
This is meant to be something like the providers page, but for individuals or small companies looking for consulting to help with installation, integration or modification of ownCloud.

WIP! 

Current look:
activity in owncloud1

TODO:
* [x] define important/relevant properties (location, size, .. ???)
* [x] define criteria for the consultants who want to be on the page and put that in a page

### CODE REVIEW

**Comment by jospoortvliet** [comment]
The 'properties' I've defined are:
* has hosting option
* for small/medium/large companies

I also want to know github accounts they are responsible for/own to see if they contribute to ownCloud. Based on those contributions they get sorted, as in, more contributions is higher on the page.

For a filtering UI I still need help but that is a future thing when the page gets bigger. For now I can handle the sorting by hand, too.

Thus, rests us to add who we already know/have and get the form ready.

Page looks like this now:
consulting - owncloud

**Comment by jospoortvliet** [comment]
and yes, I'll run it past our resident designer before publishing, it's a tad ugly now ;-)

**Comment by kelleybrooks** [comment]
It will be important to indicate what they specialize in.  For example, we recently had a request for someone who wants to distribute mobile apps en masse but was not technical enough to do so by the details contained somewhere here in GH.  There might be other folks who are experts at specific environments, etc.  I think we want to standardize these buckets of capabilities.  As this will require a transfer of money, Holger will be interested in legalese and we may choose to post things with the profile (i.e. PayPal, Credit Card, Bitcoin, Beer)--there is likely a regional limitation as well as a language piece.  

"Certified" is a tough word and as we don't offer certification, we should avoid it.  Let me know if you want to have a conversation about some of the additional criteria.

**Comment by jospoortvliet** [comment]
Added specializations:
* mobile
* app development
* branding

Any more? They are essentially free text fields and I could add any number for each provider, so this should be as flexible as we need...
consulting - owncloud website

**Comment by kelleybrooks** [comment]
By using a dropdown, you set yourself up to do a select on the site later….i.e. show me all the consultants who do mobile in Denmark, etc.
 
I think there are likely more like deployment, training, etc. I’m definitely not the expert here, but we’ll need to also be sure that we have a note about subscription from inc and what that provides so we don’t compete against ourselves.

**Comment by jospoortvliet** [comment]
After chat with Holger, here the current look and text:
screenshot

Plan forward:
- [ ] ask achim for data from the gold and silver partners on .com and add them to the page (WIP)
- [ ] talk to Jaclyn to get a form up for getting added (WIP)
- [ ] final review by Kelley, Matt and Frank
- [ ] go live!

Future:
- [ ] create a filter box on top per country and specialities
- [ ] allow adding ownCloud apps a consultant can support
- [ ] figure out a way to sync partner changes on .com with .org (also for providers)

**Comment by karlitschek** [comment]
do we also have specialized in 'installing' and 'running/configuring' ownCloud? Probably the most common thing where smbs need help from a consultant

**Comment by karlitschek** [comment]
@jancborchardt What do you think about the layout?

**Comment by jospoortvliet** [comment]
As it is hard to specify in advance what consultants can specialize in, instead I've just made it a free text field. That allowed me to copy in the text our partners have there - we can tell them/suggest to give more details later. This works and makes it simpler but I have to figure out how to make the sizes of each piece equally big :(

screenshot

**Comment by jancborchardt** [comment]
Some feedback:
* put the logos first, centered
* name below, centered
* flags right next to the name
* below that the details. Be it text or bullet points, it should not exceed 3 lines

**Comment by jospoortvliet** [comment]
* updated text based on a comment from kelley
* made the changes Jan proposed
* text will have to be at most **135** characters. I've made the height of the items fixed ("height: 130px").
* looks like I forgot to commit some of the changes at the office (sigh) so I can only add the images tomorrow.
* [ ] next up: generate the text for a submission form.

**Comment by jospoortvliet** [comment]
The application form (the questions have not yet been updated. Instead of asking for *target audience* and *type of hosting* it will ask for a 135 character description.

I also created a Consulting Guidelines document akin to the Provider Guidelines, mostly the same but with a little consulting-related detail.
apply2 - owncloud

**Comment by jancborchardt** [comment]
Few things:

* is everything in that form actually needed? Also, no need to split Contact first and last name
* do not bold the form labels. If anything use h3 for them (font-size: 15px; font-weight: 300;)
* the button looks different from the other normal ones (like Download)
* the logo info bullet point at the top is superfluous because it says below directly next to the logo upload

**Comment by jospoortvliet** [comment]
@jancborchardt the form comes from hubspot. I can control the questions asked but not the look of it. The separation of first and last name is for hubspot tracking.

**Comment by jospoortvliet** [comment]
Current look of the Consulting page. Note that this is an old branch which has many recent changes not applied, including the font, white background and other things. Also, I dunno why the logo is too big but that I will either go away when I merge or I will fix it later.
consulting - owncloud 1

**Comment by jospoortvliet** [comment]
Things are working locally and everything is ready for review. Will merge to staging and fix comments in a new PR.

**Comment by kelleybrooks** [comment]
A couple things...

-The "request to be listed on this page" link is broken
-I would call the top section (based on your written description) "ownCloud Certified Partners" and I think you need to check with Holger on who else should be there like ACP, etc
-The second section shouldn't overlap with the first

**Comment by jospoortvliet** [comment]
Fixed the points Kelley brought up as well as the idea to only show logo's for the partners. randomly made two partners unsupported to show the difference ;-)

Check on https://staging.owncloud.org/consulting

**Pull request merged**
