### PR TITLE
Installfix

### PR DESCRIPTION
**Pull request by jospoortvliet**

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Pull request for #478

**Comment by jancborchardt** [comment]
As discussed I’d say no:

Having the verson for the Sync client/apps doesn’t make sense since it’s 2 different things: desktop and mobile. And on the server it’s irrelevant for »Get providers«, or different.

So actually it’s more confusing. Let’s just not add the versions there because they will show in the popups anyway.

**Comment by jospoortvliet** [comment]
Agreed. Closing.

**Comment by tessus** [comment]
People want to see what the current version is, when going to a download page. Having them to click on something to get the most basic information is bad design.

If you don't want to add the info there, maybe you can create a page called versions or releases, where you have an overview of all current releases. Don't you think that would make sense?

**Comment by jancborchardt** [comment]
@tessus sorry, but the version is not the most basic information. The page will always offer the latest version. But you can also download older ones, or experimental ones.

The page you are looking for might be https://owncloud.org/changelog/ ?

**Comment by tessus** [comment]
@jancborchardt the changelog is for the server sw only.

I still think that version info is basic information. Anyway, this is just my personal opinion.
You mentioned earlier that for the sync client, the version numbers differ for desktop and mobile clients. The interesting thing is that even after clicking on Mobile clients, you don't get any version info at all.

Here's a conversation I had earlier:

- Hey, what's the latest version of ownCloud?
- Not sure, check the website.
- Hmm, the info is not there.
- You have to click on download to see the current version.
- No page that shows me the versions for server and clients?
- No.

**Comment by jancborchardt** [comment]
1. Go to https://owncloud.org
2. Read »ownCloud Server 8.0« in big letters directly on the front page

;)

**Comment by tessus** [comment]
@jancborchardt hahaha, you crack me up!

Exactly my point: it says 8.0, not 8.0.2. There's also no info on the client versions.

**Pull request closed without merging**
