### PR TITLE
Update strings.php

### PR DESCRIPTION
**Pull request by jnweiger**
Build succeeded. ova format is uploaded. Other formats rolling withing the next half hour...

@jospoortvliet go, go, go
@Kawohl FYI

### CODE REVIEW

**Comment by jospoortvliet** [comment]
OVA and QCOW2 are up, they work on https://staging.owncloud.org/install/#instructions-server - the others are not yet uploaded, correct?

**Comment by jnweiger** [comment]
http://download.owncloud.org/community/production/vm/
shows OVA QCOW RAW now, its the internal mirroring that takes some time... I guess. 
My upload of all 5 formats is complete

**Comment by jospoortvliet** [comment]
They are all there now so I'm going live. Thanks!

**Comment by jnweiger** [comment]
Oh, now there are six of them. We silently missed VHDX in the first batch.

**Pull request merged**
