### PR TITLE
More frontpage improvements

### PR DESCRIPTION
**Pull request by jospoortvliet**
#776 was merged to staging. let's discuss further improvements here until this all goes live.

TODO:
- [x] grey buttons need a thin border, or else they look weird when they touch
- [x] on the narrowest mobile view where there are just 2 rows of customer references, we should cut down the number of logos to 4 or 6 max. Otherwise it takes too long to scroll by.
- [x] link the customer references to actual articles / press releases, or not at all. This is mostly just to namedrop, not to lead people away from our page.
- [x] the Android screenshot mockup on the right can be improved: 1) use latest Android, not Holo 2) Use a more engaging screen than sharing settings, like a grid view of photos 3) Remove all the notifications in the header bar.
- [x] »Flexibiltiy« and »Twitter« needs to be capitalized
- [x] the text of the posts in the Twitter, news and forum section should be left-aligned
- [x] fix the ownCloud logo being on the newspaper in 1080P

### CODE REVIEW

**Comment by jancborchardt** [comment]
A few things:

- [ ] on the narrowest mobile view where there are just 2 rows of customer references, we should cut down the number of logos to 4 or 6 max. Otherwise it takes too long to scroll by.
- [ ] link the customer references to actual articles / press releases, or not at all. This is mostly just to namedrop, not to lead people away from our page.
- [ ] the Android screenshot mockup on the right can be improved: 1) use latest Android, not Holo 2) Use a more engaging screen than sharing settings, like a grid view of photos 3) Remove all the notifications in the header bar.
- [ ] »Flexibiltiy« and »Twitter« needs to be capitalized
- [ ] the text of the posts in the Twitter, news and forum section should be left-aligned

**Comment by karlitschek** [comment]
nice :+1:

**Comment by jospoortvliet** [comment]
All points fixed. Pushing some awfully big images to the repo, probably shouldn't have included them but I prefer to have them by hand in case of future changes. Going for deploy once this is ready to go.

**Comment by jancborchardt** [comment]
Fuck yes! @jospoortvliet you rule! Thanks a lot

**Comment by jancborchardt** [comment]
Now I can finally point people to our website without feeling embarassed. ;)

**Pull request merged**
