### PR TITLE
add release banners

### PR DESCRIPTION
**Pull request by jospoortvliet**
@jancborchardt adding the banners here. Can then link to them :D

### CODE REVIEW

**Comment by jancborchardt** [comment]
Just occured to me that we should also have them in double the resolution so they look good on retina-displays. Or how do the sites manage that? Otherwise every one of them will look pixelated on any newer device.

(Double-resolution images are usually saved with a `@2x` appended between filename and extension, like `/ownCloud-release-160x600@2x.png` – which then of course should be 320x1200 in size. Then the site just has to define via CSS: `width: 160px; height: 600px;` and everything will look good.)

**Comment by jospoortvliet** [comment]
Let me see if I can add that.

**Comment by jospoortvliet** [comment]
@jancborchardt done. OK?

**Comment by jancborchardt** [comment]
Yup, looking good now. Btw, you also have a 1920*1080 hidpi screen right? So you should be able to see that for when websites do not have hi-res images. Looks blurry and not good. ;)

**Pull request merged**
