### PR TITLE
update banners

### PR DESCRIPTION
**Pull request by jospoortvliet**
for ownCloud 8.1, it's coming soon ;-)

### CODE REVIEW

**Comment by jospoortvliet** [comment]
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
»coming soon« in lower case please. ;) Otherwise :+1:

**Comment by jospoortvliet** [comment]
Done.

**Comment by jancborchardt** [comment]
HOMIE! Lowercase c _and_ s of course. :D As I wrote »coming soon«.

**Comment by jospoortvliet** [comment]
shit

**Comment by jancborchardt** [comment]
:hankey:

**Pull request merged**
