### PR TITLE
updated conf page for announcement of the event dates.

### PR DESCRIPTION
**Pull request by jospoortvliet**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks good judging from the code. Do you have a screenshot or a test instance?

**Comment by jospoortvliet** [comment]
android app contributors2
android app contributors2
@jancborchardt there you go

**Comment by jancborchardt** [comment]
Nice, just 2 things:

* The sentence `Bringing ownCloud Contributors from around the world together for a week of coding, discussion, talks and fun.` should maybe be `Bringing together ownCloud Contributors from around the world<br>for a week of coding, design, discussion, talks & fun!`
* Also, instead of strong, use h3. We shouldn’t use bold typeface on that page (except for in the logo ;)

Sounds good?

**Comment by jospoortvliet** [comment]
sure, can do.

**Pull request merged**
