### PR TITLE
open sans as default to make Jan happy

### PR DESCRIPTION
**Pull request by jospoortvliet**
Trying to address #188 to make @jancborchardt happy...
old:
test6
new:
test6

Is this the right way?

### CODE REVIEW

**Comment by jancborchardt** [comment]
I’m drooling.

Only one thing. As said in https://github.com/owncloud/owncloud.org/issues/188 actually put the fonts on the server and use the fonts.css from core (just copy that into the normal CSS file) to display it. We shouldn’t have a call to Google to get the font.

**Comment by jospoortvliet** [comment]
@jancborchardt have it your way ;-)
pls have a look at this and check if it actually is correct pls, code-wise...

**Comment by jospoortvliet** [comment]
(and it does indeed look better)

**Comment by jancborchardt** [comment]
Nice! :+1:

**Comment by jancborchardt** [comment]
NOW PUSH IT LIVE! IT LOOKS AWESOME :D

**Pull request merged**
