### PR TITLE
Adding Albanian sq translation

### PR DESCRIPTION
**Pull request by ujdhesa**
Hello, 

Here you are the Albanian (sq) translation. Please merge it.

### CODE REVIEW

**Comment by meowncloud** [comment]
Internal Server Error

**Comment by jnweiger** [comment]
@ujdhesa this PR hangs for almost a year. Is it still relevant?
I am happy to help, if it is!

**Comment by ujdhesa** [comment]
@jnweiger,

Yes and no. Yes, because I wanted to add sq translation. No, because I haven’t gone through the steps required for testing it (as provided in the Readme here https://github.com/owncloud/owncloud.org )

So, rejecting the PR for now is OK.

**Comment by jnweiger** [comment]
All right. Closing for now. Please ping again, when ready.

**Pull request closed without merging**
