### PR TITLE
Frontpage

### PR DESCRIPTION
**Pull request by jospoortvliet**
@jancborchardt @karlitschek took a while and it is hackish but here's a start.

open questions:
* I feel it is pretty small now, I think that some more details about what this ownCloud thing is would fit just fine below the 'who uses ownCloud' part.

- [x] add nice images for above the three text items
- [ ] add nice image as background.
- [ ] if that image has no screenshot of ownCloud in action, add one somewhere.

owncloud

### CODE REVIEW

**Comment by karlitschek** [comment]
I like it.
A few things:
- background photo is obviously a placeholder only 
- I think the question if we use a blue navigation header or leave it transparent depends a bit on the background photo that we choose. Let's wait for that and see what looks better.
- Let's leave the social stuff (forum, twitter, ..) as it is for now. Separate discussion.
- We can add some icons/images/illustrations above the three boxes. But please keep it small. I think the focus should be on the main photo and the text.
- We need to add the hosted aspect. Let's change the middle box to "ownCloud keeps your files secure and private - you decide where you want to host your data and which server you want to use."

The rest is great!

**Comment by jospoortvliet** [comment]
Made changes. More spacing, white background. The three feature items all have a link (with a subtle mouse-over effect of dark blue and no underline) going to respectively /contribute, /???? and /features. Yes, those are not great matches. We ought to add a page on privacy and security to our site and change the features and contribute page. Right now, features essentially is "more information about ownCloud" and I contemplate linking the button in the top teaser there with a 'learn more' instead of to install.

owncloud website

**Comment by jancborchardt** [comment]
More feedback:
- the navigation header being transparent is good, and should stay like that
- change the bright blue button color to the ownCloud blue #1d2d44
- move the monthly newsletter button on the same line as the social g+, fb, twitter, rss icons
- roughly double the size (or 150% at least) of text and button in the main area (slogan, text below, action button) as currently they float lost in space
- lose the dot at the end
- add »calendars« between files and contacts in the second sentence
- a bit more vertical whitespace between each of the sections below (3 boxes, customers etc)
- I’m fine with leaving the social section for now, but please let’s cut it to 2 twitter posts, and 5 each of forum and news. In the future I would even cut the forum so we can focus on promo here – twitter and blogs
- make the customer logos just a bit smaller, more horizontal whitespace between them, and add ~3 more so they fill the same width as the 3 boxes above.
- add exactly 1 link on the bottom of each of the 3 boxes.
   - first box: »Join our community« to https://owncloud.org/contribute/
   - second box: »Install your own« to https://owncloud.org/install/#instructions-server
   - third box: »Browse apps« to https://apps.owncloud.com/index.php?xsortmode=high&page=0&xcontentmode=920x922x923x924 – we really need to redesign this and integrate it into owncloud.org
- we need somewhere on the frontpage where we put a screenshot still – nothing is more frustrating than a nice frontpage which doesn’t actually show you how the hell the product looks like. ;) I’d say between the customers and social stuff. Not sure about the exact layout yet.

**Comment by jospoortvliet** [comment]
- I did add some more customers. The customer logo's are either this size, or miniscule. That is the nature of the layouting using bootstrap and I'm not sure if I really can change that without truly advanced hackery. Help welcome...
- About the linking - the entire thing now links to it on mouse-over, I guess you prefer explicit links, that's easy.
 - contribute - sure.
 - that skips the option to choose a provider (!) and thus locks a large part of our userbase out. Let's just link to owncloud.org/install instead.
 - I don't feel good at all about liking to apps.owncloud.com - not only because it doesn't look great, but we should FIRST tell them what awesome features we have already, and capabilities like external storage (!) encryption, versioning and all the other awesome isn't even explained at all yet. I think most of those are FAR more interesting for most users than the apps, so I'd rather first send them to owncloud.org/features before the app store. We could, instead, add a prominent link to the app store on the bottom of the feature list on owncloud.org/features.
- screenshot - I agree. Could be in the main picture, a phone with ownCloud Mobile lying on the table, a laptop (Frank's Macbook, whoah) with the web UI fullscreen... Would work for me.

**Comment by jospoortvliet** [comment]
owncloud website

- [ ] I'd like to add three more customers to make it an even 12 (that way it looks best in terms of responsiveness) and I'd like to ask for suggestions on the talk ML @karlitschek

**Comment by jospoortvliet** [comment]
Add customers:
- [ ] Investment Planning Council
- [ ] Joy Global
- [ ] Health Management Associates

**Comment by jospoortvliet** [comment]
@karlitschek as far as I am concerned - the background is now the main thing still open.

**Comment by jancborchardt** [comment]
@jospoortvliet can you post a new screenshot? Some details again:

* [ ] the second line (below the main sentence) should be a single line. To achieve that, convert the two »and« into »&«. If it still exceeds the width, make the font size a tiny bit smaller until it’s only one line.
* [ ] the Download button on the top right should also have the background color #1d2d44, just like the main button
* [ ] »The latest Twitter/Forum/News« should not be bold. Also, is this really Open Sans?
* [ ] the headers for »The latest …« should be center aligned and use the same heading / text sizes as the 3-block of »open community, privacy first, capable cloud« headers
* [ ] the headers should be simpler: »Community«, »Privacy«, »Flexibility« maybe?
* [ ] typo: »… all you need to live your digital **life**«

**Comment by jospoortvliet** [comment]
* made the 2nd line a bit shorter but - if it goes to two lines or not depends on the width of the screen ;-)
* done
* everything should be Open Sans... Can't speak for the actual feed.
* done
* done
* done

**Comment by jospoortvliet** [comment]
Here's your latest screenshot. Any more changes?
BTW as part of this change, all pages on the site will go to white background and the buttons which had white backgrounds go to light gray so as to not look bad.

**Comment by danimo** [comment]
@jospoortvliet Nice. Just one question: Is this the final background image? Frank mentioned this one was only temporary, and it makes the subtitle difficult to read.

**Comment by jospoortvliet** [comment]
@danimo yeah it's a temp pic, Frank promised to make a nice one.

**Comment by jancborchardt** [comment]
> made the 2nd line a bit shorter but - if it goes to two lines or not depends on the width of the screen ;-)

@jospoortvliet I know, but it should look fine as long as the width of the screen is wider than the main site container. ;)

* [ ] actually for the background color of the dark blue buttons, use `#35537a` which is a slightly lighter and friendlier blue and also corresponds with the primary action button color in ownCloud itself
* [ ] the button background for the formerly white buttons should be `rgba(240,240,240,.9)`, with a border of `1px solid rgba(240,240,240,.9)`. Just like in the ownCloud web interface.
* [ ] can you reduce the size of the TU Berlin logo a bit? Currently it sticks out a lot.
* [ ] we should really add a screenshot or basically the image which is on the frontpage now, between the org customers and the social stuff

**Comment by jospoortvliet** [comment]
* That blue is SO MUCH BETTER!
* Yes, much nicer!
* Done. Also reduced CERN and Uni of Hawaii, now it all looks much nicer.
* I could slap it in the middle but that's weird. Why don't we, first, try to see if we can have this in the big background image? putting devices on the table which show the user interface should not be hard...

**Comment by jancborchardt** [comment]
> putting devices on the table which show the user interface should not be hard...

Yeah, works for me. That’s a good combination and keeps the content focused.

Can you take a new screenshot then? It seems that everything is fine except the image then, but just to make sure. :) Also cc @owncloud/designers for review.

**Comment by jospoortvliet** [comment]
@jancborchardt we would need a photo first... Eg something like the many pics here: https://placeit.net/stages/ipad-and-iphone-6-mockup-at-a-corporate-office-a5489 and then put the ownCloud UI on there. I can gimp stuff in, easy enough, but we'd need a base pic. @karlitschek promised to make one - that's what we wait for, then. Or we buy a stock one, those on the site I just linked to are USD 8-15 so not particularly expensive...

**Comment by Henni** [comment]
How about giving it all a little space to breath:
image

**Comment by jancborchardt** [comment]
@Henni good call, a bit less space would be even better maybe. Also I guess it should have the same width as the rest of the page so it doesn’t overflow on other widths.

Maybe it’s best to only put 5 organizations per line? Then we can have the proper space. @jospoortvliet? :)

**Comment by jospoortvliet** [comment]
@jancborchardt bootstrap is limited to 2-4-6-12 rows. Well, you can have other numbers of rows, but then it doesn't get more spacing, just margins left and right... At least as far as I can figure that's how it works. getbootstrap.com/css/#grid

**Comment by jospoortvliet** [comment]
Looked around for stock images that look kind of like what we're looking for. Or at least, what I am thinking off. They all have the problem that they have whites in the wrong places. 
We will need a picture with an area in the middle which is NOT white (empty table?) and the devices have to be on the sides somehow as the top also needs a dark background.

The text shadows help a bit but not enough...

owncloud website
owncloud website 1
owncloud website 2

**Comment by jancborchardt** [comment]
@jospoortvliet the second screenshot would work if you blur the background a bit more (or make it darker) and put a gradient from dark to transparent behind where the navigation is.

**Comment by jancborchardt** [comment]
That is, a very slight gradient, like Youtube use for their video controls.

**Comment by karlitschek** [comment]
Guys. I'm working on a picture. But I need a few day. Relax please :-)

**Comment by jospoortvliet** [comment]
@karlitschek but we're so anxious to see what you come up with ;-)

/me waits impatiently

**Comment by jospoortvliet** [comment]
Last two commits implements most changes asked for in #780

**Comment by jospoortvliet** [comment]
Here's the new image. I've cropped/resized it to 1280x720 and worked it in the gimp jpeg export to 150kb. That's a bit much still but if I go lower it really gets ugly imho with the jpeg artifacts. What do you think?
owncloud

**Comment by karlitschek** [comment]
Hmm. The text should stay in the dark area for readability. Not sure we can move stuff around to make this happen. @jancborchardt What do you think?

**Comment by Henni** [comment]
How about loading different images depending on screen size? This way mobile devices don't have to download the large image file and could be served a smaller size instead.

This would be quite easy to implement, as this image is included via CSS.
Because of this we don't have to use any new fancy picture element, but can simply apply media-queries.

I would suggest adding media-queries for:
* mobile (maybe iPhone6)
* tablet (iPad)
* desktop (1280x720 or 1920x1080)
* Retina

**Comment by jospoortvliet** [comment]
@Henni good suggestion. Let me give it a try. I'll have to make different versions of the image but I've already been playing with it and I think I can ;-)

**Comment by jancborchardt** [comment]
I think the text overlapping the image is fine since the background is still pretty dark there. Cropping or linebreaking would look strange there.

And wow, that image looks really good! Great color of the table, fits ownCloud. And the red/orange accent color draws attention to the actual ownCloud screenshot/interface.

**Comment by jancborchardt** [comment]
Maybe just moving the image a tad to the left (like 50px) would already give the main tagline more breathing space.

**Comment by jospoortvliet** [comment]
I've done some CSS magic. Here the page on a few different sizes:
~1440p:
lw-systems1
~1080p:
lw-systems1
~900p:
lw-systems1
~720p:
lw-systems1

I think that that should be fine for desktops.

But mobile is another story. I tested on my Android and it wasn't pretty:
screenshot_2015-11-25-17-47-59

After some custom css and creative image editing, this is kind'a the best I can do on mobile. The left represent what you seen on portrait, the right is landscape on my 1080P 4.7" Android phone (no screenshot visible, unfortunately)
lw-systems1
This is AFTER creating a version of the image which is quite distorted for the portrait view to ensure it would still show something... I know, you don't really see the distortion because I used liquid rescale plugin in Gimp extensively.

Ok, I edited the CSS to show this on landscape on my Android (quite nice, I think):
lw-systems1

Real look on the phone (scrolled down a little):
screenshot_2015-11-25-17-54-25

Honestly, I think we need a new photo specifically for mobile. More space to the top, items closer to each other on the bottom, at least one phone almost centered so a what ownCloud looks like is always visible.

But I wouldn't oppose already going live this way.

Thanks to @camilasan for some of her css magic and cleaning up stuff.

**Comment by jospoortvliet** [comment]
Oh and note, to save bandwidth, it loads different images for mobile, 720p, 1080p and 1440p.

**Comment by jancborchardt** [comment]
@jospoortvliet nice! Just one thing: When the second sentence breaks, it should break so the second line is »from any device, on your terms« to have each row make sense on its own. Also, the line-height should be increased a little – `line-height: 120%` or so, if that’s too little 130 maybe.

**Comment by jospoortvliet** [comment]
@jancborchardt linehight I can do but no idea how to change the breaking of the line... I can try to fine-tune the sizes but I bet that it will look just enough different on different devices that it doesn't really solve the problem. Any suggestions?

**Comment by jancborchardt** [comment]
@jospoortvliet crazy concept: put the second row in a `<span style="white-space:nowrap;">`. Then if any word of that part of the sentence wraps, the whole part will wrap.

**Comment by jospoortvliet** [comment]
@jancborchardt I was faster ;-)

Having fixed this last thing, are you :+1: this?

**Comment by jancborchardt** [comment]
@jospoortvliet I also thought about that wrapping technique, but the most important is actually that it properly splits into 2 big parts when the size is just slightly smaller. Can you add my span thingy on top? Then I’m all :+1:’s up in here.

**Comment by jospoortvliet** [comment]
@jancborchardt I did that in the commit I pushed. I did do it a little more granularly, tested it - this works really nicely, only wrapping in an annoying (but unavoidable) way when the window is real small. You will be able to test on staging. I'll try to get this merged today so you can give it a try.

**Comment by jospoortvliet** [comment]
It's on http://staging.owncloud.org - feedback welcome.

**Comment by jancborchardt** [comment]
@jospoortvliet nice! :) 2 things:

- [ ] on the narrowest mobile view where there are just 2 rows of customer references, we should cut down the number of logos to 4 or 6 max. Otherwise it takes too long to scroll by.
- [ ] the Android screenshot mockup on the right can be improved: 1) use latest Android, not Holo 2) Use a more engaging screen than sharing settings, like a grid view of photos 3) Remove all the notifications in the header bar.

**Comment by enoch85** [comment]
I just want to thank you all for a very nice look and the work you've done here.

**Comment by danimo** [comment]
Very nice! The only feedback I have is that on 1080x1920, the white ownCloud logo on the top drowns in the grey-white newspaper:

image

Not sure if this can be fixed e.g. by a CSS hack showing a different logo that contrasts better.

**Comment by jancborchardt** [comment]
@jospoortvliet did you see my feedback? :) When do we push this live btw? We can always iterate further as soon as it’s live.

**Comment by jospoortvliet** [comment]
@jancborchardt I will do the screenshot thing tomorrow and see if I can fix the thing @danimo mentioned. Then if @karlitschek agrees, I will deploy.

**Comment by karlitschek** [comment]
yes. let's push this out and do incremental improvements

**Comment by jospoortvliet** [comment]
Aaaand... it went live here: https://github.com/owncloud/owncloud.org/pull/800 ;-)

**Pull request merged**
