### PR TITLE
updated providers

### PR DESCRIPTION
**Pull request by Kawohl**
looks good on staging

### CODE REVIEW

**Comment by lefherz** [comment]
you are pushing from the wrong branch - to have a clean git history, we should pull from master into live, not from fixproviders.

**Comment by Kawohl** [comment]
Master ist dirty toVersendet mit der SolMail-App--------- Original Message ---------
From: Emil Lefherz 
To: "owncloud/owncloud.org" 
Date: Thu Nov 09 13:04:01 GMT+01:00 2017
Subject: Re: [owncloud/owncloud.org] updated providers (#1314)

you are pushing from the wrong branch - to have a clean git history, we should pull from master into live, not from fixproviders.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/owncloud/owncloud.org","title":"owncloud/owncloud.org","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/owncloud/owncloud.org"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lefherz in #1314: you are pushing from the wrong branch - to have a clean git history, we should pull from master into live, not from fixproviders."}],"action":{"name":"View Pull Request","url":"https://github.com/owncloud/owncloud.org/pull/1314#issuecomment-343134905"}}}

**Comment by lefherz** [comment]
The next time we push something from master to live, we will have these commits in live twice.

**Comment by Kawohl** [comment]
@lefherz Can you please pick my commits? And merge them in? I am in school, and very busy.

**Comment by lefherz** [comment]
yes, I will take care of it.

**Pull request closed without merging**
