### PR TITLE
App store approval form

### PR DESCRIPTION
**Pull request by jospoortvliet**
This form should be the first step in getting your app to the 'approved' state in our app store.

Upon submission, the submitter should be subscribed to the app review mailing list. This mechanism is currently NOT in place as I have no idea how to do it. Sending a specially crafted email might be able to do the trick - but then this has to be written in the PHP script handling the form: `page-appformsubmit.php`.

Thanks to @blizzz for help.

@karlitschek @jancborchardt @LukasReschke feedback is welcome. I will need help to get the mailing list submission thing to work. Thoughts?

Screenshots:
bla1
bla1

### CODE REVIEW

**Comment by jancborchardt** [comment]
Great stuff, only a few style things:

* [ ] don’t bold the labels of the input fields, that takes too much focus from the input fields themselves
* [ ] labels and inputs are too far apart. Just put them beneath each other (see example markup below)
* [ ] use plain layout with `<p>` elements instead of tables (and wrap the input inside the label), because otherwise the input field will not be focused when the text is clicked. Big no-no accessibility-wise (and generally)
* [ ] Instead of putting the explanatory text below the labels, put it as placeholder inside the input fields / textarea
* [ ] Combine the First name and Last name fields either into one, or at least into one line. That is, the label above says »Name« and the placeholder for the inputs says »First name« and »Last name«
* [ ] Cut »Your email address« to simpler »Email address«

Example of how the layout should look:
```
<p>
  <label>Name<br>
  <input type="text"></label>
</p><p>
  <label>Email address<br>
  <input type="text"></label>
</p>
```

**Comment by karlitschek** [comment]
very nice :+1:

**Comment by jospoortvliet** [comment]
bla1
All done ;-)

**Comment by jospoortvliet** [comment]
bla1
Seems to work...

**Comment by jospoortvliet** [comment]
@karlitschek @jancborchardt @MorrisJobke so - the emails are send out properly, too. so I'm going to finish this in master with a separate commit.

**Comment by jospoortvliet** [comment]
Ready for final approval and feedback at https://staging.owncloud.org/contribute/appform/ -> if I hear nothing it goes live some time next week and I'll kick out the blog post about all this ;-)

**Comment by jospoortvliet** [comment]
Just requested a deployment after merging to live https://github.com/owncloud/owncloud.org/pull/629 - we can publish this soon, thus.

**Pull request merged**
