### PR TITLE
Update press page

### PR DESCRIPTION
**Pull request by jospoortvliet**
Update for owncloud.org/press, to go live about 24-48 hours before release.

### CODE REVIEW

**Comment by jospoortvliet** [comment]
https://github.com/owncloud/screenshots/tree/stable8.0 created so link should work.

**Comment by jospoortvliet** [comment]
Added update to the owncloud.org/features page.

**Comment by tomneedham** [comment]
Fyi there is no way for this to go live now, since other improvements have been merged to master. They are blocking until the release is out.

**Comment by jospoortvliet** [comment]
@tomneedham that's good as this is meant to go live AFTER the changes that are in master (mostly owncloud.org/eight). See mail about timing!

**Pull request merged**
