### PR TITLE
more small fixes

### PR DESCRIPTION
**Pull request by jospoortvliet**
See if anything else comes up in the next few hours before we deploy again...

### CODE REVIEW

**Comment by jospoortvliet** [comment]
Footer changes are to bring the doc.o.o site and the rest of o.o in line with each other. Can't do the exact same thing as the documentation links in the .org footer are dynamic.

**Comment by jospoortvliet** [comment]
Makes the footer almost the same as https://github.com/owncloud/documentation/pull/942

I think this can be checked, merged and put live - I've had enough of the website for today.

**Comment by jospoortvliet** [comment]
@karlitschek changes aren't big... Let's test this on staging.

**Comment by karlitschek** [comment]
nice :+1:

**Pull request merged**
