### PR TITLE
desktop client: 2.3.3 rc2

### PR DESCRIPTION
**Pull request by guruz**
@stkjj @lefherz Please check on staging then deploy

### CODE REVIEW

**Comment by jnweiger** [comment]
Merge into staging, so that @lefherz can check it there.

**Comment by guruz** [comment]
@jnweiger Could do that, but page-desktop is the whole changelog.. so at some point when doing the next release you need to anyway have those previous release links

**Comment by guruz** [comment]
Tested on staging, all download links work.

@lefherz please ping when deploiyed to production

**Comment by jnweiger** [comment]
Emil checked, gave me permission to deploy. He is on the run.

**Pull request merged**
