### PR TITLE
Add changelogs for 9.1.4, 9.0.8, 8.2.10, 8.1.12

### PR DESCRIPTION
**Pull request by PVince81**
Prepared changelogs for next week.

Please review.

Don't merge before these versions are out!

### CODE REVIEW

**Comment by PVince81** [comment]
- [ ] TODO: adjust release date once tarballs are built

**Comment by PVince81** [comment]
@crrodriguez @jnweiger please review then deploy, thanks.
The announcement I will send later will point to that page.

**Comment by PVince81** [comment]
Increased release date

**Comment by davitol** [comment]
👍

**Comment by PVince81** [comment]
@crrodriguez @jnweiger please deploy

**Pull request merged**
