### PR TITLE
Remove EE changelog entries

### PR DESCRIPTION
**Pull request by PVince81**
@danimo @dragotin

### CODE REVIEW

**Comment by RealRancor** [comment]
@PVince81 If you're already modifying the changelog you also might want to move the oC 9.0.3 release at the top. Currently its below the Version 7.0.15 released on may 13 2016.

**Comment by PVince81** [comment]
@RealRancor done

The order is really weird. It's like, latest bunch at the top, then less latest bunch again...

**Comment by RealRancor** [comment]
@PVince81 Thanks! :+1: 

> The order is really weird. It's like, latest bunch at the top, then less latest bunch again...

AFAIK the order were always "latest releases" from major to minor version. However 7.0.15 to 8.2.5 where on top before 9.0.2 because these got released after 9.0.2.

Additionally https://github.com/owncloud/owncloud.org/pull/976 added some more mess in here as it had removed 8.2.5 completely.

**Comment by RealRancor** [comment]
@PVince81 Seems some other commits already changed the order and now causing a merge conflict. Sorry, shouldn't have pointed you to the ordering as this PR was only about the removal of the EE entries

**Comment by PVince81** [comment]
@RealRancor updated

**Comment by RealRancor** [comment]
:+1:

**Comment by VicDeo** [comment]
:+1:

**Pull request merged**
