### PR TITLE
Minor typos in changelog

### PR DESCRIPTION
**Pull request by phil-davis**
A few minor typos and corrections in the change log.

### CODE REVIEW

**Comment by PVince81** [comment]
Thanks :+1:

**Comment by RealRancor** [comment]
The main issue here is that the Changelog is auto-generated by a script according to the set milestone or am i wrong? So every typo within the reported issues are also ending up in the Changelog.

**Comment by PVince81** [comment]
@RealRancor unfortunately no, I had to compile all this by hand... Commit messages aren't clean enough to use a script.

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
@jnweiger @danimo what is the process to bring this online? THX

**Comment by DeepDiver1975** [comment]
> @jnweiger @danimo what is the process to bring this online? THX

let's see what happens if we simply merge it ....

**Pull request merged**
