### PR TITLE
Live

### PR DESCRIPTION
**Pull request by jospoortvliet**
I'd love to have this difference between master and live disappear - it's all empty anyway. Does that make any kind of sense, @danimo @LukasReschke @karlitschek ??

It makes it easier to see what changed when I ask for a deployment of the site.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@jospoortvliet This are al merge commits. By default Github creates them to track the history of what got merged when. You can do the merge by hand and use the fast-forward method. See https://www.git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by jospoortvliet** [comment]
@MorrisJobke yeah, I got that - and they do go away if I merge this, right?

**Comment by MorrisJobke** [comment]
> @MorrisJobke yeah, I got that - and they do go away if I merge this, right?

yes, but they will come back again if you use the github way of merging live and master ... ;)

**Comment by jospoortvliet** [comment]
I see that ;-)

But I'd like to clean it up a bit anyway, so I'll do that now.

**Pull request merged**
