### PR TITLE
rework install/#testing-development

### PR DESCRIPTION
**Pull request by lefherz**
We reworked the install page of the testing clients. Thanks to @stkjj for the final polishing.

is this nice? review on https://staging.owncloud.org/install/#testing-development @pmaier1 @jnweiger 

@Kawohl is the updated CLA information ready for going live?

### CODE REVIEW

**Comment by pmaier1** [comment]
Good job so far but for me it doesn't look that nice as the android section is not aligned with the other sections and the newsletter thingy on the bottom left overlaps (maybe not that important though).

testing_android

**Comment by lefherz** [comment]
both is intended; everything else looks worse.

**Comment by stkjj** [comment]
@pmaier1 The newsletter comes from the "normal" view and fits there fine. It's without any link presently anyway as it had the constant contact submission previously. We'll have a different approach for the new oc.org page

**Comment by lefherz** [comment]
the newsletter thingy just stays in the bottom right always, also if you scroll. if we want it to be visible at all, it is the best solution, I think.

Yes, it would be less chaotic, but we had a lot of weird looking blank space and the line break wasn't looking very good, when we tried it.

Thanks, I'll merge :)

**Comment by Kawohl** [comment]
fun thing the newsletter thingy doesn't pop up in all of my browsers on staging.owncloud.org 
I didn't even know it existed

**Comment by jnweiger** [comment]
@lefherz your two columns with owncloud and testpilotcloud side by side is missing for the nightlies
testpilotmissing

**Pull request merged**
