### PR TITLE
Update advisories and adjust layout

### PR DESCRIPTION
**Pull request by LukasReschke**
Please double check if everything does still work as expected. Did some changes to the layout as well as it seemed to be a little bit off.

Should get merged on Aug. 25.

### CODE REVIEW

**Comment by LukasReschke** [comment]
@jospoortvliet @danimo THX

**Comment by jospoortvliet** [comment]
testing...

**Comment by jospoortvliet** [comment]
looking good. Merging.

**Comment by jospoortvliet** [comment]
Will ask for deploy by end of day.

**Pull request merged**
