### PR TITLE
prepare client-2.3.3 release

### PR DESCRIPTION
**Pull request by jnweiger**
Push to staging after the packages are moved from testing to stable.
Do not push to live before official release announcements!

Test the fresh packages at https://download.owncloud.com/desktop/testing/?C=M;O=D

```
 testpilotcloud-2.3.3.8243.pkg.tbz.sig               2017-08-30 21:05   65   
[   ] testpilotcloud-2.3.3.8243.pkg.tbz                   2017-08-30 21:05   25M  
[   ] testpilotcloud-2.3.3.8243.pkg                       2017-08-30 21:05   25M  
[   ] testpilotcloud-2.3.3.8251-setup.exe                 2017-08-30 21:02   38M  
[TXT] testpilotcloud-client-2.3.3.8295.linux-repo.html    2017-08-30 21:01  969   
[   ] owncloudclient-2.3.3.tar.xz                         2017-08-30 20:58   32M  
[   ] ownCloud-2.3.3.8242.pkg.tbz.sig                     2017-08-30 20:55   65   
[   ] ownCloud-2.3.3.8242.pkg.tbz                         2017-08-30 20:55   26M  
[   ] ownCloud-2.3.3.8242.pkg                             2017-08-30 20:55   26M  
[   ] ownCloud-2.3.3.8250-setup.exe                       2017-08-30 20:52   38M  
[TXT] owncloud-client-2.3.3.8294.linux-repo.html          2017-08-30 20:49  940   
```

### CODE REVIEW

**Comment by lefherz** [comment]
Looks fine, do we want to test on staging, so we can put it live later? What would @guruz and @michaelstingl want to correct?

**Comment by guruz** [comment]
> https://download.owncloud.com/desktop/testing/owncloudclient-2.3.3-rc2.tar.xz.asc

Wrong link in changelog, rc2..

**Comment by jnweiger** [comment]
thanks for the reviews. missing asc fixed. pushed to staging.owncloud.org. 
@michaelstingl please confirm the linux deprecation list in the changelog.

**Comment by lefherz** [comment]
https://staging.owncloud.org/install/#testing-development is broken now. @stkjj can you take a look? The Desktop Clients paragraph isn't supposed to show up when $VERSIONS_CLIENT_DESKTOP_TESTING is empty, but only the testpilots-paragraph hides atm.

**Pull request merged**
